apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sentinel
  labels:
    app: backend
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: api
    spec:
      containers:
      - name: backend
        image: sentinel/backend:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: NEO4J_URI
          value: "bolt://neo4j:7687"
        - name: NEO4J_USER
          value: "neo4j"
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: password
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sentinel
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sentinel
data:
  config.yaml: |
    api:
      title: "Sentinel Intelligence Platform"
      version: "1.0.0"
      cors_origins:
        - "https://sentinel.example.com"
        - "http://localhost:3000"
    
    database:
      neo4j:
        max_connection_pool_size: 50
        connection_acquisition_timeout: 60
    
    services:
      collection:
        interval_seconds: 3600
      analytics:
        batch_size: 100
    
    security:
      classification: "UNCLASSIFIED//FOUO"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: sentinel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
