apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel

resources:
  - namespace.yaml
  - neo4j-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO

secretGenerator:
  - name: app-secrets
    literals:
      - NEO4J_PASSWORD=CHANGE_ME_IN_PRODUCTION

images:
  - name: sentinel/backend
    newName: ghcr.io/elchacal801/sentinel/backend
    newTag: latest
  - name: sentinel/frontend
    newName: ghcr.io/elchacal801/sentinel/frontend
    newTag: latest
